apiVersion: v1
kind: Service
metadata:
  name: {{ template "broker.fullname" . }}
  labels:
    app: {{ template "broker.name" . }}
    chart: {{ template "broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      nodePort: {{ .Values.service.ports.nodePort }}
      targetPort:  {{ .Values.service.ports.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "broker.name" . }}
    release: {{ .Release.Name }}
